url=jdbc:mysql://localhost:3307/fafoshop_pos?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Ho_Chi_Minh
user=fafoshop
pass=PmEnsgzC0Y8egt8GmldwS96YfruQ0qi282sGQDg76Lk=
key=EVSGHJpZ1An1_eSwMRFklgRU4yKcIZJ_YIxb3elT5Do=
